#!/bin/bash
dnf list installed mysql
if [ $? -ne 0]
then
    dnf install mysql-server -y
    if [ $? -ne 0]
    then
    echo "Mysql not installed :Failure"
    else
    echo "Mysql installed :Success"
    fi
echo "Mysql already installed :Skipped"
fi