#!/bin/bash
dnf list installed mysql
if [ $? -ne 0 ]
then
    dnf install mysql-server -y
    if [ $? -ne 0 ]
    then
    echo "Mysql not installed :Failure"
    else
    echo "Mysql installed :Success"
    fi
echo "Mysql already installed :Skipped"
fi

cat mk
mukunda
kumar
tack mk
kumar 
mukunda
File=$(cat mk)
echo "display the the content of the file $File"
while read -r line
do 
echo $line
done tac mk > hkfile
mk
mukunda
kumar
mk=$1
hk=$2
if [ $# -ne 2]
then
echo "usage $0 $mk $hk"
exit 1

