#!/bin/bash
USERID=$(id -u)
VALIDATE()
{
if [ $1 -ne 0 ] 
then
echo "Display :$2"
exit 1
else
echo "MYSQL SUCESS"   
}
if [ $USERID -ne 0 ] 
then
echo "Display :Root id  Failure"
exit 1
else
echo "Display :Root id  Sucess"
fi
dnf install mysql -y
VALIDATE $? "Inatlling mysql"
if [ $? -ne 0 ] 
then
echo "Display :$2"
exit 1
else
echo "MYSQL SUCESS"
fi
dnf install git -y
VALIDATE $? "Instlling Git"
if [ $? -ne 0 ]
then 
echo "Git Failure "
exit 1
else 
echo "Git sucess"
fi