#!/bin/bash
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
LOG_FOLDER="/var/log/shellscript-logs"
LOG_FILE=$(echo $0)
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
LOGS_FILE_NAME="$LOG_FOLDER/$LOG_FILE/$TIMESTAMP.log"

VALIDATE(){
    if [ $1 -ne 0 ] 
    then
    echo -e "$2.....$R FAILURE"
    exit 1
    else
    echo -e "$2......$G SUCCESS"
    fi
}
echo "script executed at : $TIMESTMP" &>>LOGS_FILE_NAME
if [ $USERID -ne 0 ] 
then
echo "Display :Root id  Failure"
exit 1
else
echo "Display :Root id  Sucess"
fi
dnf install mysql -y &>>LOGS_FILE_NAME
VALIDATE $? "Inatlling mysql"
if [ $? -ne 0 ] 
then
echo -e "$2 FAILURE ..$R"
exit 1
else
echo -e "$2 SUCCESS .. $G"
fi
dnf install git -y &>>LOGS_FILE_NAME
VALIDATE $? "Instlling Git"
if [ $? -ne 0 ]
then 
echo "Git Failure "
exit 1
else 
echo "Git sucess"
fi