#!/bin/bash
USERID=$(id -u)
if [ $USERID -ne 0 ] 
then
echo "Display :Root id  Failure"
exit 1
else
echo "Display :Root id  Sucess"
fi

dnf list installed mysql
if[ $? -ne 0 ]
then
   dnf install mysql -y
    if [ $? -ne 0 ] 
    then
    echo "Display :Mysql  installation Failure"
    exit 1
    else
    echo "MYSQL SUCESS"
    fi
    else
echo "Display :Mysql already there"
fi
dnf install git -y
if [ $? -ne 0 ]
then 
echo "Git Failure "
exit 1
else
echo "Git successfull"
fi
