#!/bin/bash
USERID=$(id -u)
if [$USERID -ne 0] 
then
echo "Display :Root id  Failure"
else
echo "Display :Root id  Sucess"
exit 1
fi

dnf install mysqll -y
if [$? -ne 0] 
then
echo "Display :Mysql  installation Failure"
else
echo "Display :Mysql installation Sucess"
exit 1
fi
dnf install git -y
echo "git installed"
