#!/bin/bash
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
VALIDATE(){
    if [ $1 -ne 0 ] 
    then
    echo -e "$2.....$R FAILURE"
    exit 1
    else
    echo -e "$2......$G SUCCESS"
    fi
}
if [ $USERID -ne 0 ] 
then
echo "Display :Root id  Failure"
exit 1
else
echo "Display :Root id  Sucess"
fi
for package in $@
do 
 dnf install $package &>>LOGS_FILE_NAME
 if [ $? -ne 0 ]
 then 
 dnf install $package -y &>>LOGS_FILE_NAME
 VALIDATE $? 
 echo "Install all $package"
 else
 echo "no install $package"
 fi
done